name: travel_scheduler
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  intl: ^0.20.2
  url_launcher: ^6.3.1
  uuid: ^4.4.2
  shared_preferences: ^2.5.3
  web: ^1.1.1
  file_picker: ^10.1.9
  http: ^1.4.0
  html: ^0.15.6
  desktop_drop: ^0.6.0
  pasteboard: ^0.4.0
  google_maps_flutter: ^2.12.2
  geocoding: ^4.0.0
  google_places_flutter: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
